[package]
name = "mind-palace"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.77"
leptos = { version = "0.7.5", features = ["csr"] }
leptos_meta = "0.7.5"
leptos_router = "0.7.5"
markdown = "0.3.0"
web-sys = "0.3.77"
