name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or "master" depending on your default branch
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install trunk
      run: cargo install trunk

    - name: Build
      run: trunk build --release --public-url /${GITHUB_REPOSITORY#*/}/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # or master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
